language: python

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

before_install:
- if [ "$TRAVIS_TAG" != "" ]; then sudo apt-get install pandoc; pip install pypandoc;
  fi

install:
- pip wheel --no-deps --wheel-dir=./dist .
- pip install dist/*.whl

before_script:
- pip install ddt

script: python -m unittest discover -s test

before_deploy:
- rm -rf dist/

deploy:
  provider: pypi
  user: HaebinShin
  password:
    secure: jsLPlaH9lphu7VlM3lk5ek1gLTSRDHfPE3OGJRnRAK6oGPJqY6yPnfb8rfbeO0Jqeor80+D+nMw5YGWalG0GvKPQq65b3TEFPY57WqK+cNOCjGaBITbERTKewY7x/+7h/ywBz5ZnRBsI1yTr4Ejl2mA9jHTbnlZ91E8kAsqBKZrmxp/yUy9rRvSdxVeYnnRbQ+qBKBE2bdjHMimluk2XAlVfLevQIVyfg/CwrRBFT8T/Pad94gbkVF21dqaYZMQpO8gOD3lk1YdttD64qrcDQEny7E1ur204INLhLyYfCCaYjzCS/mYBhb1ZZMAmFum+X0/vhrMpSF4kRWMTtcY9oierk5je1X4tqyonePg+LPMYljjGoMN0FJMRV9/cP84AjgkZxhR6M6GcCDRzgEqyxUu1BhFFwcvEas5/Hk32b1FCd2LIL2YYQg6Q2kbh1GDyoQDK8PWJjVa8dKYyTudBc2pgUK3nK5TiBQ0QtZSf5CEb+Gzi5PNoTaa9IHIBGYKjD+qVwNUnhIbIj5x5fR2AtaCGSjAn/4b5puyv1sQl00xMIJm/QTjSNHCNGOSOddVtR7+4g7Gp9I/HBAEDFC14FamztE9bAGkPOfMvrtqi3J5nLLQAy+eyj9NGTLVSiZZ6Fpc6BIt1m4FX5C4wi0ShujVKTAgjg36Hdl9l5csG2dQ=
  on:
    tags: true
    python: '3.6'
  skip_cleanup: true
  distributions: bdist_wheel sdist